### ISSUE TITLE
CLA vs DCO

### ISSUE THREAD

**Issue by bartjkdp** [Quixote-project/backend2#3]
For people contributing to our project we would require a CLA or DCO. I know [Gitlab recently switched to DCO](https://about.gitlab.com/2017/11/01/gitlab-switches-to-dco-license/). I like DCO more as it is more developer-friendly. What do you guys think?

**Comment by bartjkdp** [comment]
@smellems what do you think?

**Comment by smellems** [comment]
I wonder if we need it.

**Comment by bartjkdp** [comment]
For external contributors (non-Crown or non-Pleio) we probably do.

**Comment by ToferC** [comment]
I'm up for as open as we can be  :-)

**Comment by smellems** [comment]
Hi @bartjkdp 
I looked into this and the [DCO](https://developercertificate.org/) seems like a good idea for devs to say they have the right to contribute code to an OSS project.  With a DCO developers keep the copyright for their contributions (it's the same as if we had no DCO).  Also, I'm not sure how we would apply this, it seems that the signed-off DCO need to be attached to every commit..
https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

They also add that for small contributions, such as fixing spelling errors, where the content is small enough to not be considered intellectual property, can be submitted without signing the contribution for the DCO.

I was thinking we could just add the DCO text in a CONTRIBUTING file.
